#!/bin/sh
# https://bbs.archlinux.org/viewtopic.php?pid=584133#p584133

usage="usage: $0 -c {up|down} [-i increment]"
command=
increment=1%

while getopts i:h o
do case "$o" in
  i) increment=$OPTARG;;
  h) echo "$usage"; exit 0;;
  ?) echo "$usage"; exit 0;;
esac
done

shift $(($OPTIND - 1))
command=$1

if [ "$command" = "" ]; then
  echo "usage: $0 {up|down} [increment]"
  exit 0;
fi

if [ "$command" = "up" ]; then
  xbacklight -inc $increment
fi

if [ "$command" = "down" ]; then
  xbacklight -dec $increment
fi

notify-send " " -h int:value:$(xbacklight) -h string:synchronous:brightness -a "Brightness"
