#!/bin/bash
stat=""
while true 
do
  stat=" $(date +%I):$(date +%M) [$(date +%-j)]"
  if [ "$(iwgetid)" ] 
  then
    stat+=" * "
  fi
  if [ `battery | cut -d '%' -f 1` -lt 20 ]
  then
    stat+=" { BATTERY LOW: $(battery) } "
  fi
  xsetroot -name "${stat}"
	sleep 60
done
