#!/bin/sh
# https://bbs.archlinux.org/viewtopic.php?pid=584133#p584133

usage="usage: $0 -c {up|down|mute} [-i increment] [-m mixer]"
command=
increment=5%
mixer=Master

while getopts i:m:h o
do case "$o" in
  i) increment=$OPTARG;;
  m) mixer=$OPTARG;;
  h) echo "$usage"; exit 0;;
  ?) echo "$usage"; exit 0;;
esac
done

shift $(($OPTIND - 1))
command=$1

if [ "$command" = "" ]; then
  echo "usage: $0 {up|down|mute} [increment]"
  exit 0;
fi

display_volume=0

if [ "$command" = "up" ]; then
  display_volume=$(amixer set $mixer $increment+ unmute | grep -m 1 "%]" | cut -d "[" -f2|cut -d "%" -f1)
fi

if [ "$command" = "down" ]; then
  display_volume=$(amixer set $mixer $increment- unmute | grep -m 1 "%]" | cut -d "[" -f2|cut -d "%" -f1)
fi

if [ "$command" = "mute" ]; then
  if amixer get Master | grep "\[on\]"; then
    display_volume=0
    amixer set $mixer mute
  else
    amixer set "Headphone" unmute
    amixer set "Speaker" unmute
    display_volume=$(amixer set $mixer unmute | grep -m 1 "%]" | cut -d "[" -f2|cut -d "%" -f1)
  fi
fi


notify-send " " -h int:value:$display_volume -h string:synchronous:volume -a "Volume"
