#!/bin/sh

# Update prayer times for the day in crontab
# yearly schedule parsed in res/prayers.txt 
# (copy from yearly process in scndry/prayer)

cd /home/u/git/scripts || exit
res='res/out.cron'
tmp=$(echo 'mkstemp(/tmp/pomoXXXXXX)' | m4)


d=$(date +%-j)
d=$((d*5-4)) # first line of prayers (Fajir)
p=$(sed -n "$d,$((d+4))p" $res)

touch "$tmp"
crontab -l > "$tmp"

sed -i '/^# PRAYER START/,/^# PRAYER END/{/^#/!{/^\$/!d}}' "$tmp" # delete old

IFS='
'
for i in $p
do
  sed -i "/^# PRAYER START/a $i" "$tmp" # add in reverse chronological order
done

crontab "$tmp" 
rm "$tmp"
