#!/bin/sh

# Update prayer times for the day in crontab
# yearly schedule parsed in res/prayers.txt 
# (copy from yearly process in scndry/prayer)

cd /home/u/git/scripts
script=`pwd`'/auto/prayer-notify'
res='res/out.cron'
tmp='/tmp/tmp.txt'


d=`date +%-j`
d=$(($d*6-5)) # first line of prayers (Fajir)
p=`sed -n "$d,$(($d+5))p" $res`

touch $tmp
crontab -l > $tmp

sed -i '/^# PRAYER START/,/^# PRAYER END/{/^#/!{/^\$/!d}}' $tmp # delete old

IFS='
'
for i in $p
do
  sed -i "/^# PRAYER START/a $i" $tmp # add in reverse chronological order
done

crontab $tmp 
rm $tmp
