#! /bin/sh

sleep 0.3
level=`cat /sys/class/backlight/intel_backlight/brightness`
level=`echo $level/10|bc -l`

notify-send -t 1000 " " -h int:value:$level -h string:synchronous:volume \
	-a "levels/bright" 
