#! /bin/sh
query=$(cat ~/.config/bm.txt | dmenu -i -l 10 -p 'net')
[ -z "$query" ] && exit 1

if [ "$(echo "$query" | /bin/grep -c '^http\|^www\.\|\.[[:alpha:]]\+$')" = '1' ] && [ "$(echo "$query" | /bin/grep -c '[[:space:]]')" = '0' ] 
then
  [ "$(echo $query | /bin/grep -c '^http')" != '1' ] && query="https://$query"
  (firefox --new-window "$query")
else
  (firefox --new-window "https://kagi.com/search?q=$query")
fi
