#! /bin/sh
query=$(dmenu -i -l 10 -p 'net' < ~/.config/bm.txt)
[ -z "$query" ] && exit 1

url=$(echo "$query" | "$AUTO/xurls")
if [ -n "$url" ]
then
   (firefox --new-window "$url")
else
   (firefox --new-window "https://kagi.com/search?q=$query")
fi
