#! /bin/sh
query=$({
[ -t 0 ] || cat
cat -- "$XDG_CONFIG_HOME/bm.txt"
} | dmenu -i -l 10 -p 'net')

[ -z "$query" ] && exit 1

# NOTE: see `sh->heredocs`
url=$("$AUTO/xurls" << URL    
$query   
URL
)

if [ -n "$url" ] 
then
  (firefox --new-window "$url")
elif [ "${query%% *}" = '!d' ] 
then
  (firefox --new-window "https://devdocs.io/#q=$query")
else
  query=$("$AUTO/query-string-encode" 'q' "$query")
  (firefox --new-window "https://kagi.com/search?$query")
fi
