#!/bin/sh
# NOTE:Dependencies: xinput
# TEST:

# Device does not exist
! xinput --list-props "$1" > /dev/null && exit 1
state="$(xinput --list-props "$1" | grep 'Device Enabled' | cut -d ':' -f 2 | tr -d ' \t')"
if [ "$state" = "1" ]; then
  xinput --disable "$1"
else
  xinput --enable "$1"
fi
