#!/usr/bin/python
import subprocess as sp
import sys


def get_state(device: str) -> bool:
    cmd = f'xinput --list-props "{device}" | grep "Device Enabled"'
    ps = sp.Popen(cmd,
                  shell=True,
                  stdout=sp.PIPE,
                  stderr=sp.STDOUT)
    out = ps.communicate()[0]
    out = " ".join(out.decode()
                      .rstrip()
                      .strip()
                      .split())
    return bool(int(out[-1]))


if sys.argv[1] == "--toggle":
    device = sys.argv[2]
    if get_state(device):
        state = "disable"
        sp.call(f"notify-send -t 1500 -a \"scripts/devtogle\" \
                \"{device}\" disabled", shell=True)
    else:
        state = "enable"
        sp.call(f"notify-send -t 1500 -u critical -a \"scripts/devtogle\" \
                \"{device}\" enabled", shell=True)
    sp.call(f"xinput {state} \"{device}\"", shell=True)
