#! /bin/sh
#ext=`echo $@|rev|cut -d '.' -f 1|rev` 
mtype=$(mimetype -L "$@" | cut -d ':' -f 2 | tr -d ' ')
fname=$(echo "$1" | rev | cut -d '/' -f 1 | rev)
case $mtype in
  *image*)
    chafa --size=60x -w 1 "$@"
    ;;
  *audio* | *video*)
    kid3-cli -c 'get' "$fname" | bat --tabs 2 -n --color always --terminal-width -20
    ;;
  *application/zip* )
    unzip -l "$fname"
    ;;
  *)
    bat --tabs 2 -n --color always --terminal-width -20 "$@"
    ;;
esac
