#!/bin/sh
xdotool mousemove 1920 0
stamp=$(date +%s)
maim "$HOME/ss-$stamp.png"

prompt=$(printf 'y\nn' | dmenu -p 'crop image ?')
[ "$(printf "%s" "$prompt" | grep -ci 'y')" = 1 ] && cropgui "$HOME/ss-$stamp.png"

prompt=$(printf 'y\nn' | dmenu -p "view ss-$stamp-crop.png ?")
if [ "$(printf "%s" "$prompt" | grep -ci 'y')" = 1 ] 
then
  sxiv "$HOME/ss-$stamp-crop.png"
  prompt=$(printf 'y\nn' | dmenu -p 'upload to imgur ?')
  [ "$(printf "%s" "$prompt" | grep -ci 'y')" = 1 ] && imgurbash2 "$HOME/ss-$stamp-crop.png"
fi
