#!/bin/sh

while true 
do
	stat=

	#date
	date=`date "+^c#FFFFFF^%I^c#00af87^:^c#FFFFFF^%M ^c#00af87^[^c#FFFFFF^%a %d %b^c#00af87^]^c#FFFFFF^"`
	stat=$stat" $date "

	# battery
	battery=`cut -d '%' -f 1 /sys/class/power_supply/BAT0/capacity`
  charge=
  [ $battery -ge 99 ] && \
		stat=$stat"^b#00af87^^c#000000^"
  [ $battery -lt 75 ] && \
		stat=$stat"^b#ff8700^^c#000000^"
  [ $battery -lt 20 ] && \
		stat=$stat"^b#FF0000^^c#ffffff^                    "
	stat=$stat" $battery% "

  xsetroot -name "$stat"
	sleep 60
done
