#!/bin/sh
# Notify volume level

case $1 in
	up)
    vol=$(wpctl get-volume @DEFAULT_SINK@ | head -n 1 | awk '{print $2 * 100}')
    [ "$vol" -ne 100 ] && wpctl set-volume @DEFAULT_SINK@ 0.05+;sh "$AUTO"/vol-notif 
		;;
	down) 
    wpctl set-volume @DEFAULT_SINK@ 0.05-;sh "$AUTO"/vol-notif 
		;;
	mute) 
    wpctl set-mute @DEFAULT_SINK@ toggle;sh "$AUTO"/vol-notif 
		;;
esac
