#!/bin/sh
# Notify volume level

case $1 in
	up)
    [ `pactl get-sink-volume @DEFAULT_SINK@ | /bin/grep -o "[[:digit:]]\+%" | head -1 | tr -d '%'` -ne 100 ] && pactl set-sink-volume @DEFAULT_SINK@ +1%;sh $AUTO/vol-notif 
		;;
	down) 
    pactl set-sink-volume @DEFAULT_SINK@ -1%;sh $AUTO/vol-notif 
		;;
	mute) 
    pactl set-sink-mute @DEFAULT_SINK@ toggle;sh $AUTO/vol-notif 
		;;
esac
