#!/bin/sh
# Notify volume level

vol=$(wpctl get-volume @DEFAULT_SINK@ | head -n 1 | awk '{print $2 * 100}')
string=$(wpctl get-volume @DEFAULT_SINK@ | head -n 1 | awk '{print $3}')

notify-send "Vol: $string" \
    -a 'levels/vol' \
    -t 1000 \
    -h "int:value:$vol" \
    -h string:x-dunst-stack-tag:audio
