#!/bin/sh
# vim: tw=0
XAUTHORITY="/home/u/.runtime/Xauthority"
DISPLAY=":0"
export XAUTHORITY DISPLAY

xsetwacom --display $DISPLAY set "Wacom Intuos S Pen stylus" Mode "Relative"

xsetwacom --display $DISPLAY set "Wacom Intuos S Pen stylus" Button 2 "pan"
xsetwacom --display $DISPLAY set "Wacom Intuos S Pen stylus" Button 3 "pan"
xsetwacom --display $DISPLAY set "Wacom Intuos S Pen stylus" PanScrollThreshold 100
# xsetwacom --display $DISPLAY set "Wacom Intuos S Pen stylus" Rotate cw

xsetwacom --display $DISPLAY set "Wacom Intuos S Pad pad" Button 1 "key ctrl c -ctrl ctrl v -ctrl" 
xsetwacom --display $DISPLAY set "Wacom Intuos S Pad pad" Button 2 "key ctrl v -ctrl" 
#xsetwacom --display $DISPLAY set "Wacom Intuos S Pad pad" Button 3 "key +ctrl + shift i -ctrl -shift"
xsetwacom --display $DISPLAY set "Wacom Intuos S Pad pad" Button 8 "key shift l -shift" # Vimium (foreward)
