#!/bin/sh
# vim: tw=0
XAUTHORITY="/home/u/.runtime/Xauthority"
DISPLAY=":0"
export XAUTHORITY DISPLAY

xsetwacom --display $DISPLAY set "Wacom Intuos BT S Pen stylus" Mode "Relative"

xsetwacom --display $DISPLAY set "Wacom Intuos BT S Pen stylus" Button 2 "pan"
xsetwacom --display $DISPLAY set "Wacom Intuos BT S Pen stylus" Button 3 "pan"
xsetwacom --display $DISPLAY set "Wacom Intuos BT S Pen stylus" PanScrollThreshold 100
xsetwacom --display $DISPLAY set "Wacom Intuos BT S Pen stylus" CursorProximity 42

xsetwacom --display $DISPLAY set "Wacom Intuos BT S Pad pad" Button 1 "3" 
xsetwacom --display $DISPLAY set "Wacom Intuos BT S Pad pad" Button 2 "3" 
xsetwacom --display $DISPLAY set "Wacom Intuos BT S Pad pad" Button 3 "3"
xsetwacom --display $DISPLAY set "Wacom Intuos BT S Pad pad" Button 8 "3"
