#! /bin/sh

export DISPLAY=:0 
export XAUTHORITY=/home/u/.runtime/Xauthority
export XDG_RUNTIME_DIR="$HOME/.runtime"

BEEP=/home/u/.config/zsh/beep.wav

vol=60
pactl set-sink-mute @DEFAULT_SINK@ 0
pactl set-sink-volume @DEFAULT_SINK@ "${vol}%"
paplay $BEEP

notify-send.sh -t 0 -u critical -a "Sleep Warning" "" "<b>Sleep</b> in 15 minutes"
