#! /bin/sh


sound_alarm() {
  org_vol=`pulsemixer --get-volume | cut -d' ' -f 1`
  mut=`pulsemixer --get-mute`
  vol=100
  [ "$1" ] && vol="$1"

  sleep 1                                            &&\
    pulsemixer --unmute --set-volume $vol            &&\
    mpv $BEEP --no-terminal                          &&\
    pulsemixer --set-volume $org_vol                 &&\
    [ $mut -eq 1 ] && pulsemixer --mute              &
  sleep 1
}

while :
do 
 sound_alarm $1
done
