#!/bin/sh

export DISPLAY=:0 
export XAUTHORITY=/home/u/.runtime/Xauthority
export XDG_RUNTIME_DIR="$HOME/.runtime"

BEEP=/home/u/.config/zsh/beep.wav

vol="${1:-90}"

k() {
  doas kill -9 $(pgrep "$@")
}

k pipewire
k wireplumber
k pipewire-pulse
(
pipewire &
wireplumber &
pipewire-pulse &
)

sound_alarm() {
  wpctl set-volume @DEFAULT_SINK@ "${vol}%"
  wpctl set-mute @DEFAULT_SINK@ 0
  pw-play "$BEEP"
  sleep 1
}

while :
do 
  sound_alarm
done &
