#!/bin/sh

export DISPLAY=:0 
export XAUTHORITY=/home/u/.runtime/Xauthority
export XDG_RUNTIME_DIR="$HOME/.runtime"

BEEP=/home/u/.config/zsh/beep.wav

vol="${1:-80}"

sound_alarm() {
  pactl set-sink-volume @DEFAULT_SINK@ "${vol}%"
  pactl set-sink-mute @DEFAULT_SINK@ 0
  paplay "$BEEP"
  sleep 1
}

while :
do 
  sound_alarm
done &
