#!/bin/sh
# NOTE: GNU SED EXTENSIONS USED.
# NOTE: :noexport: headings are not converted

org_file=$1
deck="import"
deck=$(sed -n '/^#+ANKI_DECK/p' $1|cut -d ' ' -f 2-)
[ -n "$2" ] && deck=$2

out_file="anki/${org_file%%.org}.anki.org"
[ ! -d anki ] && mkdir anki
[ -e "$out_file" ] && rm -f "$out_file"

sed -e '/^\*\s* :noexport:/,$d' \
-e "s/^\* \(.\+\)/* Item\n:PROPERTIES:\n:ANKI_NOTE_TYPE: Basic\n:END:\n** Front\n\1/" \
-e '/^\.$/d' \
-e '/^:/d' \
-e '/^SCHEDULED/d' \
-e 's/:drill://' \
-e 's/[[:blank:]]*$//' "$org_file" > "$out_file"

sed -i "1s/^/#+PROPERTY: ANKI_DECK $deck\n/" "$out_file"

emacs  -nw --kill "$out_file" -f anki-editor-mode -f anki-editor-push-notes
