#!/bin/sh
gpgfile=$(find ~/.local/share/pass -type f -name '*.gpg' |
  sed 's/.*\/\(.*\)\.gpg$/\1/' | dmenu -i -p "Pass:")

case $gpgfile in
  '')
    :
    ;;
  *-otp)
    st -c "pass" -g "60x12+660+426" -t "passm" -t "passm" -e /bin/pass otp -c "$gpgfile"
    /bin/pass otp -c "$gpgfile"
    ;;
  *)
    st -c "pass" -g "60x12+660+426" -t "passm" -e /bin/pass show -c "$gpgfile"
    /bin/pass show -c "$gpgfile"
    ;;
esac
