#!/bin/sh

if [ -z "$1" ]
then
  password=$(find ~/.local/share/pass -type f -name '*.gpg' |
    sed 's/.*\/\(.*\)\.gpg$/\1/' | dmenu -i -p "Pass:")
  op=" -c"
else
  password="$1"
  op=
fi

case $password in
  '')
    exit 1
    ;;
  *-otp)
    eval "/bin/pass otp $op $password"
    ;;
  *)
    eval "/bin/pass show $op $password"
    ;;
esac
