#! /bin/sh

org_vol=`pulsemixer --get-volume | cut -d' ' -f 1`
mut=`pulsemixer --get-mute`

brf=$2
vol=80

[ ! $brf ] && brf="Break."

sleep $1		 									 						        &&\
	notify-send.sh -u critical -a scripts/pomo $brf &&\
	pulsemixer --unmute --set-volume $vol 	 			  &&\
	paplay $BEEP								 						 			  &&\
	pulsemixer --set-volume $org_vol 				 			  &&\
	[ $mut -eq 1 ] && pulsemixer --mute 		 			  &
