#!/bin/sh
# TEST:
dt=$(date +%s)
tmp=$(echo 'mkstemp(/tmp/pomoXXXXXX)' | m4)
script=/home/u/git/scripts/alias/alert

parse() {
  ret=$(echo "$1" | grep -o "[[:digit:]]\+$2" | tr -d "$2" | paste -sd+ | bc -l)
  if [ -z "$ret" ]; then
    echo 0
  else
    echo "$ret"
  fi
}

accumulate_delta() {
  tot=0

  hrs=$(parse "$1" h)
  min=$(parse "$1" m)
  sec=$(parse "$1" s)

  hrs=$(echo "$hrs * 3600" | bc -l)
  min=$(echo "$min * 60" | bc -l)
  tot=$(echo "$sec + $hrs + $min" | bc -l)
}

# TODO: Refactor this later to use getopt.
[ -z "$1" ] && echo '[Err] no args given.' && exit 1

IFS=' ' read -r delta << EOF
$1
EOF

IFS='
'
accumulate_delta "$delta"

ping_time=$(echo "$dt + $tot" | bc -l)
dt=$(date "+%M %H %d %b" --date="@$ping_time" | tr '[:upper:]' '[:lower:]')

if [ -z "$2" ] 
then
  note="pomo $1"
else
 shift 1
 note="$*"
fi

crontab -l > "$tmp"
ln="$dt * $script '$note'"
sed -i "/^# TIMERS START/a $ln" "$tmp"
crontab "$tmp"
rm "$tmp"
doas sv restart crond
