#! /bin/sh

org_vol=`pulsemixer --get-volume | cut -d' ' -f 1`
mut=`pulsemixer --get-mute`
brf="$2"
vol=80
out=`mktemp`

# Span of pomodoro
# start=`date +"%a %I:%M %P"`
# delta=`echo $1 | sed -e "s/s/seconds/g" -e "s/h/hours/g" -e "s/m/minutes/g"` 
# end=`date -d "$date +$delta" +"%a %I:%M %P"`
# span="$start - $end"

[ ! "$brf" ] && brf="Break."

nohup snore -d $1 > $out                            &&\
  rm -r $out                                        &&\
  notify-send.sh -u critical -a scripts/pomo "$brf" &&\
  pulsemixer --unmute --set-volume $vol             &&\
  mpv $BEEP --no-terminal                           &&\
  pulsemixer --set-volume $org_vol                  &&\
  [ $mut -eq 1 ] && pulsemixer --mute               &
