#!/bin/sh
# NOTE:Dependencies: xinput, xdotool
# TEST:
filename="$1"
path="${filename%/*}" 
filename=${filename##*/}
ext="$2"

wid="$(cat /tmp/termid.dat)"
comm() {
  if ! xdotool getwindowclassname "$wid"
  then 
    n "[Err] No out terminal found"
    exit
  fi

  xdotool key --window "$wid" 'Escape'
  xdotool key --window "$wid" 'ctrl+c'
  xdotool key --window "$wid" 'i' 'BackSpace'
  xdotool key --window "$wid" Enter 

  xdotool type --window "$wid" "wdir='$path'"
  xdotool key --window "$wid" Enter 

  xdotool type --window "$wid" \
    "(cd \$wdir && export RUNFILE=$filename && "
  xdotool type --window "$wid" "$*)"
  xdotool key --window "$wid" Enter 

}
case "$ext" in
  python)
    comm "python $filename"
    ;;
  java)
    comm "javac $filename && java ${filename%.*}"
    ;;
  sh)
    comm "sh $filename"
    ;;
  awk)
    comm "awk -f $filename 'times.txt' > out.txt"
    ;;
  gnuplot)
    comm "gnuplot -persist $filename"
    ;;
  c)
    comm "make run"
    ;;
  cpp)
    comm "make run"
    ;;
  tex)
    comm "xelatex -jobname=out -output-directory=/tmp $filename"
    ;;
  sql) # using litecli
    xdotool key --window "$wid" 'ctrl+c'
    xdotool type --window "$wid" ".read $filename"
    xdotool key --window "$wid" 'Enter'
    ;;
  '')
    :
    ;;
  *)
    :
    ;;
esac

xinput --enable 'keyboard:Corne Keyboard'
