#!/bin/sh
cd -- "${0%/*}" || exit 1
. ../header

stt 'sc-cast-recording'

file="$REC_DIR/$(date +%b%d.mp4)"
[ -e "$file" ] && printf "file exists\n" && exit 1

nice \
ffmpeg -probesize 20M -video_size 1920x1080 -framerate 30 \
-f x11grab -draw_mouse 0 -i :0.0 \
-c:v libx264 -pix_fmt yuv420p \
-filter:v "eq=saturation=1.8,eq=contrast=1.2,setpts=0.5*PTS" \
"$file"
