#! /bin/sh
# NOTE: Dependencies: rfkill, rtcwake, dwmc
# NOTE: see alarm-loop
# NOTE: see ../periodic/periodic
# TEST:

parse() {
  ret=$(echo "$@" | grep -o "[[:digit:]]\+$2" | tr -d "$2" | paste -sd+ | bc -l)
  echo "${ret:-0}"
}

duration() {
  hrs=$(parse "$1" h)
  min=$(parse "$1" m)
  sec=$(parse "$1" s)

  echo "${hrs}hours ${min}minutes ${sec}seconds"
}

dur=$(duration "$@")

alarm-loop 70
sleep 1

doas rfkill block bluetooth
doas rfkill block wlan

doas rtcwake -a -m mem --time "$(date -u --date="$(date) +$dur" +%s)"

sh /home/u/git/scripts/periodic/periodic
doas rfkill unblock bluetooth
doas rfkill unblock wlan
